name: Emergency Clear Vercel Container Registry

on:
  workflow_dispatch: # Позволяет запустить очистку вручную одной кнопкой

jobs:
  clear-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Force Link and Delete Registry
        run: |
          vercel link --yes --token ${{ secrets.VERCEL_TOKEN }}
          vercel vcr rm vlad3ekos-projects/see-later-telegram/bgutil --yes --token ${{ secrets.VERCEL_TOKEN }}
